module.exports.erc20Tokens = [
    ["USDT", "USDTToken", "Tether"],
    ["USDC", "USDCToken", "USD Coin"],
    ["BUSD", "BUSDToken", "Binance USD"],
    ["SHIB", "SHIBToken", "Shiba Inu"],
    ["STETH", "STETHToken", "Lido Staked Ether"],
    ["DAI", "DAIToken", "Dai"],
    ["MATIC", "MATICToken", "Polygon"],
    ["LEO", "LEOToken", "Leo Token"],
    ["WBTC", "WBTCToken", "Wrapped Bitcoin"],
    ["OKB", "OKBToken", "OKB"],
    // ["FTT", "FTTToken", "FTX"],
    // ["LINK", "LINKToken", "Chainlink"],
    // ["CRO", "CROToken", "Cronos"],
    // ["UNI", "UNIToken", "Uniswap"],
    // ["XCN", "XCNToken", "Chain"],
    // ["FRAX", "FRAXToken", "Frax"],
    // ["APE", "APEToken", "ApeCoin"],
    // ["MANA", "MANAToken", "Decentraland"],
    // ["SAND", "SANDToken", "The Sandbox"],
    // ["LDO", "LDOToken", "Lido DAO"],
    // ["AXS", "AXSToken", "Axie Infinity"],
    // ["QNT", "QNTToken", "Quant"],
    // ["AAVE", "AAVEToken", "Aave"],
    // ["CHZ", "CHZToken", "Chiliz"],
    // ["TUSD", "TUSDToken", "TrueUSD"],
    // ["USDP", "USDPToken", "Pax Dollar"],
    // ["CUSDC", "CUSDCToken", "cUSDC"],
    // ["CETH", "CETHToken", "cETH"],
    // ["HBTC", "HBTCToken", "Huobi BTC"],
    // ["GRT", "GRTToken", "The Graph"],
    // ["HT", "HTToken", "Huobi"],
    // ["SNX", "SNXToken", "Synthetix Network"],
    // ["USDD", "USDDToken", "USDD"],
    // ["BIT", "BITToken", "BitDAO"],
    // ["CDAI", "CDAIToken", "cDAI"],
    // ["FTM", "FTMToken", "Fantom"],
    // ["MKR", "MKRToken", "Maker"],
    // ["USDN", "USDNToken", "Neutrino USD"],
    // ["GT", "GTToken", "Gate"],
    // ["CEL", "CELToken", "Celsius Network"],
    // ["NEXO", "NEXOToken", "NEXO"],
    // ["PAXG", "PAXGToken", "PAX Gold"],
    // ["BAT", "BATToken", "Basic Attention"],
    // ["ENJ", "ENJToken", "Enjin Coin"],
    // ["CUSDT", "CUSDTToken", "cUSDT"],
    // ["AMP", "AMPToken", "Amp"],
    // ["WAVES", "WAVESToken", "Waves"],
    // ["LRC", "LRCToken", "Loopring"],
    // ["FXS", "FXSToken", "Frax Share"],
    // ["CRV", "CRVToken", "Curve DAO"],
    // ["10SET", "TenSETToken", "Tenset"],
    // ["TKX", "TKXToken", "Tokenize Xchange"],
    // ["XAUT", "XAUTToken", "Tether Gold"],
    // ["1INCH", "OneINCHToken", "1inch"],
    // ["GNO", "GNOToken", "Gnosis"],
    // ["RPL", "RPLToken", "Rocket Pool"],
    // ["OMI", "OMIToken", "ECOMI"],
    // ["GALA", "GALAToken", "Gala"],
    // ["HOT", "HOTToken", "Holo"],
    // ["ENS", "ENSToken", "Ethereum Name Service"],
    // ["XDC", "XDCToken", "XDC Network"],
    // ["CVX", "CVXToken", "Convex Finance"],
    // ["GUSD", "GUSDToken", "Gemini Dollar"],
    // ["COMP", "COMPToken", "Compound"],
    // ["YFI", "YFIToken", "yearn.finance"],
    // ["CVXCRV", "CVXCRVToken", "Convex CRV"],
    // ["OHM", "OHMToken", "Olympus"],
    // ["SRM", "SRMToken", "Serum"],
    // ["ANKR", "ANKRToken", "Ankr"],
    // ["BAL", "BALToken", "Balancer"],
    // ["LPT", "LPTToken", "Livepeer"],
    // ["RSR", "RSRToken", "Reserve Rights"],
    // ["OMG", "OMGToken", "OMG Network"],
    // ["ZRX", "ZRXToken", "0x"],
    // ["GLM", "GLMToken", "Golem"],
    // ["SYN", "SYNToken", "Synapse"],
    // ["AUDIO", "AUDIOToken", "Audius"],
    // ["ELG", "ELGToken", "Escoin"],
    // ["MIM", "MIMToken", "Magic Internet Money"],
    // ["SUSHI", "SUSHIToken", "Sushi"],
    // ["EURT", "EURTToken", "Euro Tether"],
    // ["NU", "NUToken", "NuCypher"],
    // ["MC", "MCToken", "Merit Circle"],
    // ["IMX", "IMXToken", "Immutable X"],
    // ["DAO", "DAOToken", "DAO Maker"],
    // ["UMA", "UMAToken", "UMA"],
    // ["DYDX", "DYDXToken", "dYdX"],
    // ["LUSD", "LUSDToken", "Liquity USD"],
    // ["SXP", "SXPToken", "SXP"],
    // ["KNC", "KNCToken", "Kyber Network Crystal"],
    // ["ALUSD", "ALUSDToken", "Alchemix USD"],
    // ["XCM", "XCMToken", "Coinmetro"],
    // ["SKL", "SKLToken", "SKALE"],
    // ["MXC", "MXCToken", "MXC"],
    // ["POLY", "POLYToken", "Polymath"],
    // ["WOO", "WOOToken", "WOO Network"],
    // ["VGX", "VGXToken", "Voyager VGX"],
    // ["ELON", "ELONToken", "Dogelon Mars"],
    // ["ELON", "ELONToken", "Dogelon Mars"],
    // ["PLA", "PLAToken", "PlayDapp"],
    // ["LOOKS", "LOOKSToken", "LooksRare"],
    // ["CET", "CETToken", "CoinEx"],
    // ["RNDR", "RNDRToken", "Render"],
    // ["METIS", "METISToken", "Metis"],
    // ["CEEK", "CEEKToken", "CEEK Smart VR"],
    // ["FX", "FXToken", "Function X"],
    // ["SPELL", "SPELLToken", "Spell"],
    // ["PUNDIX", "PUNDIXToken", "Pundi X"],
    // ["MVL", "MVLToken", "MVL"],
    // ["BONE", "BONEToken", "Bone ShibaSwap"],
    // ["NEST", "NESTToken", "Nest Protocol"],
    // ["EURS", "EURSToken", "STASIS EURO"],
    // ["TRIBE", "TRIBEToken", "Tribe"],
    // ["REN", "RENToken", "REN"],
    // ["KIRO", "KIROToken", "Kirobo"],
    // ["IBEUR", "IBEURToken", "Iron Bank EURO"],
    // ["PROM", "PROMToken", "Prom"],
    // ["CVC", "CVCToken", "Civic"],
    // ["PLTC", "PLTCToken", "PlatonCoin"],
    // ["SNT", "SNTToken", "Status"],
    // ["MPL", "MPLToken", "Maple"],
    // ["ORBS", "ORBSToken", "Orbs"],
    // ["WCFG", "WCFGToken", "Wrapped Centrifuge"],
    // ["EVER", "EVERToken", "Everscale"],
    // ["TITAN", "TITANToken", "TitanSwap"],
    // ["INJ", "INJToken", "Injective"],
    // ["FOLD", "FOLDToken", "Manifold Finance"],
    // ["ALICE", "ALICEToken", "My Neighbor Alice"],
    // ["SSV", "SSVToken", "SSV Network"],
    // ["NMR", "NMRToken", "Numeraire"],
    // ["API3", "API3Token", "API3"],
    // ["COTI", "COTIToken", "COTI"],
    // ["XYO", "XYOToken", "XYO Network"],
    // ["PEOPLE", "PEOPLEToken", "ConstitutionDAO"],
    // ["TEL", "TELToken", "Telcoin"],
    // ["MX", "MXToken", "MX"],
    // ["CHR", "CHRToken", "Chromia"],
    // ["CDT", "CDTToken", "Blox"],
    // ["SETH2", "SETH2Token", "sETH2"],
    // ["RLY", "RLYToken", "Rally"],
    // ["CELR", "CELRToken", "Celer Network"],
    // ["BTSE", "BTSEToken", "BTSE Token"],
    // ["DKA", "DKAToken", "dKargo"],
    // ["VLX", "VLXToken", "Velas"],
    // ["XMON", "XMONToken", "XMON"],
    // ["BNT", "BNTToken", "Bancor Network"],
    // ["RAD", "RADToken", "Radicle"],
    // ["UOS", "UOSToken", "Ultra"],
    // ["EXRD", "EXRDToken", "e-Radix"],
    // ["BICO", "BICOToken", "Biconomy"],
    // ["MULTI", "MULTIToken", "Multichain"],
    // ["SURE", "SUREToken", "inSure DeFi"],
    // ["DENT", "DENTToken", "Dent"],
];